### ISSUE TITLE
pdfium binary not found in executable created by pyinstaller

### ISSUE THREAD

**Issue by moming975** [pypdfium2-team/pypdfium2#120]
When I ran the code, everything was fine.

But when I packaged the code as an EXE, it ran wrong.

```
D:\Develop\Support\Push.AI.OCR\dist>app.exe
[38472] WARNING: file already exists but should not: C:\Users\CHENYO~1\AppData\Local\Temp\_MEI384722\torch\_C.cp36-win_amd64.pyd
Traceback (most recent call last):
  File "app.py", line 6, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "apphelper\image.py", line 17, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "pypdfium2\__init__.py", line 6, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "pypdfium2\_namespace.py", line 6, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "pypdfium2\_pypdfium.py", line 863, in <module>
  File "pypdfium2\_pypdfium.py", line 551, in __call__
ImportError: Could not load pdfium.
[4836] Failed to execute script 'app' due to unhandled exception!
```

**Comment by mara004** [comment]
I'm currently a library developer only and never used PyInstaller, so I'm afraid I might not be of much help in this case.
Nevertheless, I can provide some information about pypdfium2's internals. Perhaps this will help you identify the problem on your own.

In the installation directory of pypdfium2[^1], you'll find the files `_pypdfium.py` and `pdfium.dll`, among others.
`_pypdfium.py` are the ctypesgen-created bindings, which look for a binary named `pdfium.dll` in the same directory.

Apparently, in your case, the binary is not found, which suggests that PyInstaller may just have skipped the file. Maybe there are rules you can adjust defining which file types are included by PyInstaller?

[^1]: For me on openSUSE Linux, it is `~/.local/lib/python3.10/site-packages/pypdfium2/`

**Comment by mara004** [comment]
You may want to take a look at this pyinstaller documentation:
https://pyinstaller.org/en/stable/operating-mode.html#analysis-finding-the-files-your-program-needs
If that's not sufficient, please consider to ask the pyinstaller team.

**Comment by mara004** [comment]
Or perhaps it troubles pyinstaller that our wheels are currently wrongly flagged as `Root-Is-Purelib: true` (see `~/.local/lib/python3.10/site-packages/pypdfium2-2.4.1.dist-info/WHEEL`)?

I'll play around with thre `bdist_wheel` subclass defined in `setupsrc/pl_setup/setup_base.by` that is submitted to setuptools and see if I can change this.

**Comment by moming975** [comment]
> _pypdfium

Thank you, I copy the required DLL to the exe directory, the program can run normally

**Comment by mara004** [comment]
Okay, fine.
