### ISSUE TITLE
Allow avoiding use of ProcessPoolExecutor in render_topil

### ISSUE THREAD

**Issue by shshe** [pypdfium2-team/pypdfium2#121]
First off, thank you so much for building out this library - love that we're able to use pdfium from within our Python codebase.

In our setup, we primarily use Celery to run asynchronous tasks. We use Celery prefork workers which use the multiprocessing library underneath the hood. This conflicts with ProcessPoolExecutor raising this error:

```
Traceback (most recent call last):
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/app-RnXbbLtS-py3.8/lib/python3.8/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/app-RnXbbLtS-py3.8/lib/python3.8/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/ubuntu/app/core/tasks.py", line 453, in cache_page_images_pypdf
    for page_num, image_bytes in pypdf.get_page_images(
  File "/home/ubuntu/app/core/pypdf.py", line 50, in get_page_images
    for page_number, image in zip(page_numbers, renderer):
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/viaduct-RnXbbLtS-py3.8/lib/python3.8/site-packages/pypdfium2/_helpers/document.py", line 453, in render_topil
    yield from self._render_base("pil", **kwargs)
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/viaduct-RnXbbLtS-py3.8/lib/python3.8/site-packages/pypdfium2/_helpers/document.py", line 425, in _render_base
    for result, index in pool.map(invoke_renderer, page_indices):
  File "/home/ubuntu/.pyenv/versions/3.8.12/lib/python3.8/concurrent/futures/process.py", line 674, in map
    results = super().map(partial(_process_chunk, fn),
  File "/home/ubuntu/.pyenv/versions/3.8.12/lib/python3.8/concurrent/futures/_base.py", line 608, in map
    fs = [self.submit(fn, *args) for args in zip(*iterables)]
  File "/home/ubuntu/.pyenv/versions/3.8.12/lib/python3.8/concurrent/futures/_base.py", line 608, in <listcomp>
    fs = [self.submit(fn, *args) for args in zip(*iterables)]
  File "/home/ubuntu/.pyenv/versions/3.8.12/lib/python3.8/concurrent/futures/process.py", line 645, in submit
    self._start_queue_management_thread()
  File "/home/ubuntu/.pyenv/versions/3.8.12/lib/python3.8/concurrent/futures/process.py", line 584, in _start_queue_management_thread
    self._adjust_process_count()
  File "/home/ubuntu/.pyenv/versions/3.8.12/lib/python3.8/concurrent/futures/process.py", line 608, in _adjust_process_count
    p.start()
  File "/home/ubuntu/.pyenv/versions/3.8.12/lib/python3.8/multiprocessing/process.py", line 118, in start
    assert not _current_process._config.get('daemon'), \
AssertionError: daemonic processes are not allowed to have children
```

We've worked around the issue by monkey patching the ProcessPoolExecutor with this:
```python
import pypdfium2._helpers.document as pdfium_helpers_document

class SerialProcessPoolExecutor:
    def __init__(*args, **kwargs):
        pass

    def map(self, func, args):
        for arg in args:
            result = func(arg)
            yield result

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc_value, exc_traceback):
        pass


# HACK: monkey-patch ProcessPoolExecutor
pdfium_helpers_document.ProcessPoolExecutor = SerialProcessPoolExecutor
```

It would be great if the library supported this execution mode where multiprocessing / ProcessPoolExecutor is optional.

**Comment by mara004** [comment]
Only document level rendering is implemented using `ProcessPoolExecutor` (`PdfDocument.render_...()`) while page level rendering is not concurrent (`PdfPage.render_...()`) – so this is already optional.

**Comment by shshe** [comment]
Appreciate the quick response! I missed the `PdfPage.render_...()` functions - using that works just fine. Thanks for your work on this project!

**Comment by mara004** [comment]
Nice, thanks for the response!
