### ISSUE TITLE
Test suite randomly segfaults

### ISSUE THREAD

**Issue by mara004** [pypdfium2-team/pypdfium2#127]
Probably caused by recent changes. Need to investigate.

**Comment by mara004** [comment]
Ok, obviously caused by 5dec9ba1af4f558e29607a1221cfd27b7e60826b but I'm not sure why.

**Comment by mara004** [comment]
Well, according to my tests, it works correctly if dropping https://github.com/pypdfium2-team/pypdfium2/commit/1cef25746fdd3a1e1acb917f47d9d1523624280c but that's virtually impossible. That was a documentation-only change...

**Comment by mara004** [comment]
When running the test suite inside `gdb` using ` gdb --args python3 -m pytest tests/`, in case of a segmentation fault, the top of the backtrace always looked like this:
```
Thread 1 "python3" received signal SIGSEGV, Segmentation fault.
0x00007ffff16c6300 in ?? () from /usr/lib64/python3.10/lib-dynload/_ctypes.cpython-310-x86_64-linux-gnu.so
(gdb) bt
#0  0x00007ffff16c6300 in ?? () from /usr/lib64/python3.10/lib-dynload/_ctypes.cpython-310-x86_64-linux-gnu.so
#1  0x00007ffff0699cfa in CPDFSDK_FormFillEnvironment::~CPDFSDK_FormFillEnvironment() () from /home/manuel/projects/pypdfium2/src/pypdfium2/pdfium
#2  0x00007ffff06b4353 in FPDFDOC_ExitFormFillEnvironment () from /home/manuel/projects/pypdfium2/src/pypdfium2/pdfium
```

This makes me suspect it might have had something to do with form filling.
Anyway, it looks like I can't reproduce it since https://github.com/pypdfium2-team/pypdfium2/commit/33f7966e28013890da0cac76ae790b529713eacf anymore.

**Comment by mara004** [comment]
Ok, it really is related to forms, see https://github.com/pypdfium2-team/pypdfium2/commit/2b1ddbd4354532607e74c297c329e544a8864243
