### ISSUE TITLE
PdfContext is no longer supported

### ISSUE THREAD

**Issue by zachwvk** [pypdfium2-team/pypdfium2#144]
```python
import pypdfium2 as pdfium

...

with pdfium.PdfContext(outpath) as pdf:
    image = pdfium.render_page_topil(pdf, 0)
    image.save(outname)
```

Produces the following error:
`AttributeError: module 'pypdfium2' has no attribute 'PdfContext'`

But if I roll back to pypdfium2 version 1.0.0 then this code works successfully. 

I figure this is something I need to change/fix in how I use pypdfium2, but I think it would be worth having some notes in the [ChangeLog](https://github.com/pypdfium2-team/pypdfium2/blob/58a9d2f13198791f4771e9cf8ea0362f444d352b/docs/source/changelog.md) that say that the PdfContext is no longer supported. It would be helpful for me at least if some tips were provided for migration. 

I've tried this
```python
with pdfium.PdfDocument(outpath) as pdf:
    image = list(pdf.render_to(pdfium.BitmapConv.pil_image))[0]
    image.save(outname)
```

Which is producing a RuntimeError in `render_to`

**Comment by mara004** [comment]
Using `PdfDocument()` instead of `PdfContext()` is correct.
The RuntimeError in `render_to()` sounds unrelated, however. Please post the traceback so that I can take a look.

**Comment by mara004** [comment]
The changelog for v2 said `Entirely re-implemented the support model [...] All helpers are now object-oriented.`
This means basically everything changed, so you should just read the updated docs.
pypdfium2's userbase is quite small and I'm the only active developer, so it's not justifiable to waste time on additional migration notes.

**Comment by zachwvk** [comment]
Thanks for your prompt reply, and work on this package.

I'm performing this operation on a pdf's that I've generated using other
software. They always only have one page.

That said your recommendation is still valid, I'll try it tomorrow, and let
you know.

Zach

**Comment by zachwvk** [comment]
Thanks again

Using
```
with pdfium.PdfDocument(outpath) as pdf:
        page = pdf.get_page(0)
        image = page.render_to(pdfium.BitmapConv.pil_image)
        image.save(outname)
        page.close()
```
works perfectly. I don't know why `image = list(pdf.render_to(pdfium.BitmapConv.pil_image))[0]` was throwing that runtime error, but I think I've totally moved on anyway. 

Here is the trace you asked for, but again, it's not important to me if this works or not:
<pre><code>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\__My__Python__Path__\Python310\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\__My__Python__Path__\Python310\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\__My__Python__Path__\Python310\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\__My__Python__Path__\Python310\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\__My__Python__Path__\Python310\lib\runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\__My__Python__Path__\Python310\lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\__My__Python__Path__\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "W:\hw\Scripts\AfterGenOutputs.py", line 332, in <module>
    SplitPDF.Bookmarks(OutputStatus["PDF"]["files"][0])
  File "W:\hw\Scripts\SplitPDF.py", line 184, in Bookmarks
    <b>image = list(pdf.render_to(pdfium.BitmapConv.pil_image))[0]</b>
  File "C:\__My__Python__Path__\Python310\lib\site-packages\pypdfium2\_helpers\document.py", line 523, in render_to
    for result, index in pool.map(invoke_renderer, page_indices):
  File "C:\__My__Python__Path__\Python310\lib\concurrent\futures\process.py", line 761, in map
    results = super().map(partial(_process_chunk, fn),
  File "C:\__My__Python__Path__\Python310\lib\concurrent\futures\_base.py", line 610, in map
    fs = [self.submit(fn, *args) for args in zip(*iterables)]
  File "C:\__My__Python__Path__\Python310\lib\concurrent\futures\_base.py", line 610, in <listcomp>
    fs = [self.submit(fn, *args) for args in zip(*iterables)]
  File "C:\__My__Python__Path__\Python310\lib\concurrent\futures\process.py", line 732, in submit
    self._adjust_process_count()
  File "C:\__My__Python__Path__\Python310\lib\concurrent\futures\process.py", line 692, in _adjust_process_count
    self._spawn_process()
  File "C:\__My__Python__Path__\Python310\lib\concurrent\futures\process.py", line 709, in _spawn_process
    p.start()
  File "C:\__My__Python__Path__\Python310\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\__My__Python__Path__\Python310\lib\multiprocessing\context.py", line 336, in _Popen
    return Popen(process_obj)
  File "C:\__My__Python__Path__\Python310\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\__My__Python__Path__\Python310\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "C:\__My__Python__Path__\Python310\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "W:\hw\Scripts\AfterGenOutputs.py", line 332, in <module>
    SplitPDF.Bookmarks(OutputStatus["PDF"]["files"][0])
  File "W:\hw\Scripts\SplitPDF.py", line 184, in Bookmarks
    <b>image = list(pdf.render_to(pdfium.BitmapConv.pil_image))[0]</b>
  File "C:\__My__Python__Path__\Python310\lib\site-packages\pypdfium2\_helpers\document.py", line 523, in render_to
    for result, index in pool.map(invoke_renderer, page_indices):
  File "C:\__My__Python__Path__\Python310\lib\concurrent\futures\process.py", line 570, in _chain_from_iterable_of_lists
    for element in iterable:
  File "C:\__My__Python__Path__\Python310\lib\concurrent\futures\_base.py", line 621, in result_iterator
    yield _result_or_cancel(fs.pop())
  File "C:\__My__Python__Path__\Python310\lib\concurrent\futures\_base.py", line 319, in _result_or_cancel
    return fut.result(timeout)
  File "C:\__My__Python__Path__\Python310\lib\concurrent\futures\_base.py", line 458, in result
    return self.__get_result()
  File "C:\__My__Python__Path__\Python310\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
</code></pre>

**Comment by mara004** [comment]
Hmm, this error message is new to me, but according to the description you are missing an `if __name__ == '__main__':` guard before calling the main function. This seems to be something specific to the `spawn` multiprocessing strategy (see also https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods).
While the `page.render_to()` approach is fine if you really intend to render just one page in the process in question, note that `pdf.render_to()` is considerably faster at rendering multiple pages (because it uses a process pool).
