### ISSUE TITLE
Source installation fails on Ubuntu 20.04

### ISSUE THREAD

**Issue by mara004** [pypdfium2-team/pypdfium2#163]
Ctypesgen fails while parsing `fpdf_edit.h`, resulting in an unfinished bindings file:
```
  INFO: Status: Preprocessing /tmp/tmpkct3tegv.h
  INFO: Status: gcc -E -U __GNUC__ -dD "-D__extension__=" "-D__const=const" "-D__asm__(x)=" "-D__asm(x)=" "-DCTYPESGEN=1" "/tmp/tmpkct3tegv.h"
  ERROR: gcc -E: In file included from /home/.../projects/pypdfium2/data/linux_x64/build_tar/include/fpdf_edit.h:10,
  ERROR: gcc -E:                  from /tmp/tmpkct3tegv.h:6:
  ERROR: gcc -E: /usr/lib/gcc/x86_64-linux-gnu/9/include/stdint.h:9:16: fatal error: stdint.h: No such file or directory
  ERROR: gcc -E:     9 | # include_next <stdint.h>
  ERROR: gcc -E:       |                ^~~~~~~~~~
  ERROR: gcc -E: compilation terminated.
  INFO: Status: Parsing /tmp/tmpkct3tegv.h
  INFO: Status: Processing description list.
  INFO: Status: Writing to /home/.../projects/pypdfium2/data/linux_x64/_pypdfium.py.
  INFO: Status: Wrapping complete.
```

Error when importing pypdfium2:
```
Traceback (most recent call last):
  File "/home/.../.local/bin/pypdfium2", line 5, in <module>
    from pypdfium2.__main__ import main
  File "/home/.../projects/pypdfium2/src/pypdfium2/__init__.py", line 6, in <module>
    from pypdfium2._namespace import *
  File "/home/.../projects/pypdfium2/src/pypdfium2/_namespace.py", line 8, in <module>
    from pypdfium2._helpers import *
  File "/home/.../projects/pypdfium2/src/pypdfium2/_helpers/__init__.py", line 6, in <module>
    from pypdfium2._helpers.bitmap import *
  File "/home/.../projects/pypdfium2/src/pypdfium2/_helpers/bitmap.py", line 11, in <module>
    from pypdfium2._helpers._internal import consts, utils
  File "/home/.../projects/pypdfium2/src/pypdfium2/_helpers/_internal/consts.py", line 49, in <module>
    pdfium.FPDF_COLORSPACE_UNKNOWN:    "?",
AttributeError: module 'pypdfium2._pypdfium' has no attribute 'FPDF_COLORSPACE_UNKNOWN'
```

Dependencies:
```
Ctypesgen 1.1.1-1-g12854ed
GCC 9.4.0
```

**Comment by mara004** [comment]
@nilason Do you know what might be causing this bug?

Here's what `cat /usr/lib/gcc/x86_64-linux-gnu/9/include/stdint.h` returns:
```
#ifndef _GCC_WRAP_STDINT_H
#if __STDC_HOSTED__
# if defined __cplusplus && __cplusplus >= 201103L
#  undef __STDC_LIMIT_MACROS
#  define __STDC_LIMIT_MACROS
#  undef __STDC_CONSTANT_MACROS
#  define __STDC_CONSTANT_MACROS
# endif
# include_next <stdint.h>
#else
# include "stdint-gcc.h"
#endif
#define _GCC_WRAP_STDINT_H
#endif
```

**Comment by nilason** [comment]
What gives `ldd --version ldd`?

**Comment by mara004** [comment]
> What gives ldd --version ldd?

`ldd (Ubuntu GLIBC 2.31-0ubuntu9.9) 2.31`

**Comment by nilason** [comment]
Maybe https://github.com/umlaeute/v4l2loopback/issues/129 could give you any hint?

**Comment by nilason** [comment]
See also https://gcc.gnu.org/onlinedocs/cpp/Wrapper-Headers.html

**Comment by mara004** [comment]
Thanks for the feedback, I think it's broken system headers indeed. That was a relative's device, so I don't know exactly how it got into this state, but he says something went wrong with the last kernel installation. I'll send him the fix proposed in https://github.com/umlaeute/v4l2loopback/issues/129#issuecomment-285987361.

**Comment by nilason** [comment]
Glad to help!
