### ISSUE TITLE
pypdfium2 on S390x (ubuntu22.04)

### ISSUE THREAD

**Issue by sandeepb2013** [pypdfium2-team/pypdfium2#313]
### Checklist

- [X] I confirm to be using an **official package** of `pypdfium2` from `PyPI` or `GitHub/pypdfium2-team`.
- [X] I have read and acknowledged the [response policy](https://github.com/pypdfium2-team/pypdfium2#contributions).

### Description

```
Collecting pypdfium2==0.7.0
  Downloading pypdfium2-0.7.0.tar.gz (283 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 283.0/283.0 kB 5.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [51 lines of output]
      Cloning into '/tmp/pip-install-7pg5yzok/pypdfium2_4b1a7bde13d04c959f78c22011e153e6/sourcebuild/depot_tools'...
      Checking patch gclient_scm.py...
      error: while searching for:
            # to stdout
            self.Print('')
          cfg = gclient_utils.DefaultIndexPackConfig(url)
          clone_cmd = cfg + ['clone', '--no-checkout', '--progress']
          if self.cache_dir:
            clone_cmd.append('--shared')
          if options.verbose:

      error: patch failed: gclient_scm.py:1005
      error: gclient_scm.py: patch does not apply
      Errors:
        failed to resolve infra/3pp/tools/git/linux-s390x@version:2@2.41.0.chromium.11 (line 24): no such package: infra/3pp/tools/git/linux-s390x
        failed to resolve infra/3pp/tools/cpython3/linux-s390x@version:2@3.11.8.chromium.35 (line 21): no such package: infra/3pp/tools/cpython3/linux-s390x
      /tmp/pip-install-7pg5yzok/pypdfium2_4b1a7bde13d04c959f78c22011e153e6/sourcebuild/depot_tools/bootstrap_python3: line 32: bootstrap-2@3.11.8.chromium.35_bin/python3/bin/python3: No such file or directory
      Bundled Python 3.11 not found. Use VPYTHON_BYPASS if prebuilt cpython not available on this platform: open /tmp/pip-install-7pg5yzok/pypdfium2_4b1a7bde13d04c959f78c22011e153e6/sourcebuild/depot_tools/.cipd_bin/.cipd/pkgs/0/Q0Cp0RrnNtgKaxaeq4XKs9qiPu1botnPjuw_0EWxduUC/3.11/.versions/cpython3.cipd_version: no such file or directory
      Errors:
        failed to resolve infra/3pp/tools/git/linux-s390x@version:2@2.41.0.chromium.11 (line 24): no such package: infra/3pp/tools/git/linux-s390x
        failed to resolve infra/3pp/tools/cpython3/linux-s390x@version:2@3.11.8.chromium.35 (line 21): no such package: infra/3pp/tools/cpython3/linux-s390x
      /tmp/pip-install-7pg5yzok/pypdfium2_4b1a7bde13d04c959f78c22011e153e6/sourcebuild/depot_tools/bootstrap_python3: line 32: bootstrap-2@3.11.8.chromium.35_bin/python3/bin/python3: No such file or directory
      Bundled Python 3.11 not found. Use VPYTHON_BYPASS if prebuilt cpython not available on this platform: open /tmp/pip-install-7pg5yzok/pypdfium2_4b1a7bde13d04c959f78c22011e153e6/sourcebuild/depot_tools/.cipd_bin/.cipd/pkgs/0/Q0Cp0RrnNtgKaxaeq4XKs9qiPu1botnPjuw_0EWxduUC/3.11/.versions/cpython3.cipd_version: no such file or directory
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-7pg5yzok/pypdfium2_4b1a7bde13d04c959f78c22011e153e6/setup.py", line 19, in <module>
          build_pdfium.main(DefaultArgs)
        File "/tmp/pip-install-7pg5yzok/pypdfium2_4b1a7bde13d04c959f78c22011e153e6/build_pdfium.py", line 275, in main
          patch_pdfium()
        File "/tmp/pip-install-7pg5yzok/pypdfium2_4b1a7bde13d04c959f78c22011e153e6/build_pdfium.py", line 132, in patch_pdfium
          _apply_patchset(PdfiumPatches, PDFiumDir)
        File "/tmp/pip-install-7pg5yzok/pypdfium2_4b1a7bde13d04c959f78c22011e153e6/build_pdfium.py", line 126, in _apply_patchset
          run_cmd(f"git apply -v {patch}", cwd=cwd)
        File "/tmp/pip-install-7pg5yzok/pypdfium2_4b1a7bde13d04c959f78c22011e153e6/build_pdfium.py", line 75, in run_cmd
          subprocess.run(command, cwd=cwd, shell=True)
        File "/usr/lib/python3.10/subprocess.py", line 503, in run
          with Popen(*popenargs, **kwargs) as process:
        File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-7pg5yzok/pypdfium2_4b1a7bde13d04c959f78c22011e153e6/sourcebuild/pdfium'
      Using DepotTools-provided binaries.
      DepotTools: Download ...
      git clone --depth 1 https://chromium.googlesource.com/chromium/tools/depot_tools.git /tmp/pip-install-7pg5yzok/pypdfium2_4b1a7bde13d04c959f78c22011e153e6/sourcebuild/depot_tools
      git apply -v /tmp/pip-install-7pg5yzok/pypdfium2_4b1a7bde13d04c959f78c22011e153e6/sourcebuild/patches/gclient_scm.patch
      PDFium: Download ...
      /tmp/pip-install-7pg5yzok/pypdfium2_4b1a7bde13d04c959f78c22011e153e6/sourcebuild/depot_tools/gclient config --unmanaged https://pdfium.googlesource.com/pdfium.git
      /tmp/pip-install-7pg5yzok/pypdfium2_4b1a7bde13d04c959f78c22011e153e6/sourcebuild/depot_tools/gclient sync --no-history --shallow
      git apply -v /tmp/pip-install-7pg5yzok/pypdfium2_4b1a7bde13d04c959f78c22011e153e6/sourcebuild/patches/public_headers.patch
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
```

### Install Info

```shell
Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
Linux-6.6.2-s390x-with-glibc2.35
WARNING: Package(s) not found: pypdfium2
```

### Validity

- [X] I confirm that I ran all commands, and pasted the whole output.

**Comment by mara004** [comment]
Another hint: If you have libreoffice, you might be able to just use the pdfium binary it ships with.
For me it is `/usr/lib/libreoffice/program/libpdfiumlo.so`. Just symlink to `/usr/local/lib/libpdfium.so` or something, determine the pdfium version, and then use the ["system-provided binary" installation mode](https://github.com/pypdfium2-team/pypdfium2?tab=readme-ov-file#install-source-system).

**Comment by mara004** [comment]
Regarding the failure of implicit sourcebuild, this seems to be due to outdated patches. I can see it's a bit problematic we're using latest pdfium with potentially non-latest patches.

~~Newer versions do not trigger an implicit sourcebuild anymore if no binary was found. I think it's better for callers to consciously invoke the build process if desired.~~

**Comment by sandeepb2013** [comment]
Hi @mara004 ,

Thanks for quick response.
   https://github.com/bblanchon/pdfium-binaries/issues/93.
   `Possible values

  - "x86"
  - "x64"
  - "arm"
  - "arm64"
  - "mipsel"
  - "mips64el"
  - "s390x"
  - "ppc64"
  - "riscv32"
  - "riscv64"
  - "e2k"
  - "loong64"`

**Comment by mara004** [comment]
Yes, these are the architectures listed by the toolchain's help. `s390x` may be possible indeed.
But what do you want to express with that? Again, as for adding a binary package, you'd have to discuss that with upstream. The binaries aren't built here, just repacked with a python wrapper.

**Comment by mara004** [comment]
Closing; further actions are up to affected users and pdfium-binaries.
